sudo: false
language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev # required for the --verify flag of kcov

before_script:
  - ./scripts/build-kcov
  - export PATH=$HOME/kcov/bin:$PATH

cache:
  - cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --all --verbose
  - cargo test --all --verbose
  - cargo test --all --verbose --features test-thread-log
  - cargo doc --all --verbose
  - cargo bench --verbose
  - cargo bench --verbose --features test-thread-log

after_success:
  - scripts/build-kcov
  - scripts/coverage
  - bash <(curl -s https://codecov.io/bash) && echo "Uploaded code coverage"

env:
  global:
    - RUST_BACKTRACE=1

branches:
  only:
    - master
