language: rust

cache:
  - cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --all --verbose
  - cargo test --all --verbose
  - cargo doc --all --verbose
  - cargo bench --verbose

env:
  global:
    - RUST_BACKTRACE=1
